# Generated by Django 5.1.6 on 2025-03-28 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_article_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('location', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('conferencia', 'Conferencia'), ('taller', 'Taller'), ('reunion', 'Reunión'), ('otros', 'Otros')], max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.member')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
    ]
