# Generated by Django 5.1.6 on 2025-03-25 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_member_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='created_by',
        ),
    ]
