# Generated by Django 5.1.6 on 2025-09-08 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='description',
            field=models.TextField(blank=True, help_text='Descripción del miembro para mostrar en la página de líderes', null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='is_leader',
            field=models.BooleanField(default=False, help_text='¿Es un líder de proyecto?'),
        ),
        migrations.AddField(
            model_name='member',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='URL del perfil de LinkedIn', null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='position',
            field=models.CharField(blank=True, help_text='Posición/título del miembro', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='member',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='roles',
            field=models.ManyToManyField(blank=True, to='web.role'),
        ),
        migrations.AlterField(
            model_name='member',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
